// ADR-004 Phase0補修: Scope DOM queries under the calc-sprint root to avoid collisions when embedded in a portal.
const appRoot = document.querySelector('.calc-sprint') ?? document;
const byId = (id) => appRoot.querySelector(`#${id}`);
const qs = (selector) => appRoot.querySelector(selector);
const qsa = (selector) => appRoot.querySelectorAll(selector);

const domRefs = {
  screens: {
    'profile-select': byId('profile-select-screen'),
    title: byId('title-screen'),
    'stage-select': byId('stage-select-screen'),
    settings: byId('settings-screen'),
    'dash-game': byId('dash-game-screen'),
    'dash-result': byId('dash-result-screen'),
    game: byId('game-screen'),
    result: byId('result-screen'),
  },
  profileSelect: {
    buttons: qsa('[data-profile-id]'),
    continueButton: byId('profile-select-continue'),
    selectedLabel: byId('profile-select-current'),
  },
  title: {
    startButton: byId('title-start-button'),
    freeButton: byId('title-free-button'),
    dashButton: byId('title-dash-button'),
  },
  dashGame: {
    backButton: byId('dash-game-back-button'),
    distance: byId('dash-game-distance'),
    timeRemaining: byId('dash-game-time'),
    streak: byId('dash-game-streak'),
    enemyWrap: byId('dash-game-enemy'),
    enemyBar: byId('dash-game-enemy-bar'),
    enemyText: byId('dash-game-enemy-text'),
    question: byId('dash-game-question'),
    answerInput: byId('dash-game-answer-input'),
    feedback: byId('dash-game-feedback'),
    submitButton: byId('dash-game-submit-button'),
    keypadToggle: byId('dash-game-keypad-toggle'),
    keypad: byId('dash-game-keypad'),
    keypadButtons: qsa('#dash-game-keypad [data-keypad-key]'),
  },
  dashResult: {
    backButton: byId('dash-result-back-button'),
    message: byId('dash-result-message'),
    record: byId('dash-result-record'),
    distance: byId('dash-result-distance'),
    correctCount: byId('dash-result-correct'),
    wrongCount: byId('dash-result-wrong'),
    accuracy: byId('dash-result-accuracy'),
    missRate: byId('dash-result-miss-rate'),
    maxStreak: byId('dash-result-max-streak'),
    timeRemaining: byId('dash-result-time'),
  },
  stageSelect: {
    list: byId('stage-select-list'),
    backButton: byId('stage-select-back-button'),
    freeButton: byId('stage-select-free-button'),
  },
  settings: {
    presetSelect: byId('settings-preset'),
    presetDescription: byId('settings-preset-description'),
    presetDescriptionText: byId('settings-preset-text'),
    presetTag: byId('settings-preset-tag'),
    modeInputs: qsa('input[name="mode"]'),
    digitInputs: qsa('input[name="digit"]'),
    carryCheckbox: byId('settings-carry'),
    playButton: byId('settings-play-button'),
    profileButton: byId('settings-profile-button'),
    title: byId('settings-title'),
    profileResetButton: byId('settings-profile-reset'),
    adminResetWrap: byId('settings-admin-reset'),
    adminResetButton: byId('settings-admin-reset-button'),
  },
  game: {
    hud: qs('.game-hud'),
    timeLeft: byId('game-time-left'),
    correctCount: byId('game-correct-count'),
    wrongCount: byId('game-wrong-count'),
    distance: byId('game-distance'),
    speed: byId('game-speed'),
    reviewProgress: byId('game-review-progress'),
    timeProgressBar: byId('time-progress-bar'),
    timeProgressRunner: byId('time-progress-runner'),
    question: byId('game-question'),
    answerInput: byId('game-answer-input'),
    feedback: byId('game-feedback'),
    submitButton: byId('game-submit-button'),
    keypadToggle: byId('game-keypad-toggle'),
    keypad: byId('game-keypad'),
    keypadButtons: qsa('#game-keypad [data-keypad-key]'),
    runner: byId('runner-sprite'),
    runLayer: qs('.run-layer'),
    runWorld: qs('.run-world'),
    runBgFar: qs('.run-bg--far'),
    runBgNear: qs('.run-bg--near'),
    speedLines: qs('.speed-lines'),
    runnerWrap: qs('.runner-wrap'),
  },
  result: {
    bestToast: byId('result-best-toast'),
    defaultActions: byId('result-default-actions'),
    stagePanel: byId('result-stage-panel'),
    stageName: byId('result-stage-name'),
    stageStatus: byId('result-stage-status'),
    stageMessage: byId('result-stage-message'),
    stageUnlock: byId('result-stage-unlock'),
    stageActions: byId('result-stage-actions'),
    stageRetryButton: byId('result-stage-retry-button'),
    stageNextButton: byId('result-stage-next-button'),
    stageSelectButton: byId('result-stage-select-button'),
    reviewBanner: byId('result-review-banner'),
    reviewMessage: byId('result-review-message'),
    nextActionButton: byId('result-next-action-button'),
    correctCount: byId('result-correct-count'),
    wrongCount: byId('result-wrong-count'),
    totalAnswered: byId('result-total-answered'),
    accuracy: byId('result-accuracy'),
    avgTime: byId('result-avg-time'),
    distanceRow: byId('result-distance-row'),
    distance: byId('result-distance'),
    rawDistance: byId('result-raw-distance'),
    bonusDistance: byId('result-bonus-distance'),
    distanceMultiplier: byId('result-distance-multiplier'),
    title: byId('result-title'),
    titleMessage: byId('result-title-message'),
    titleHint: byId('result-title-hint'),
    rateAdd: byId('result-rate-add'),
    rateSub: byId('result-rate-sub'),
    rateMul: byId('result-rate-mul'),
    rateDiv: byId('result-rate-div'),
    bestAvgTime: byId('result-best-avg'),
    wrongAdd: byId('result-wrong-add'),
    wrongSub: byId('result-wrong-sub'),
    wrongMul: byId('result-wrong-mul'),
    wrongDiv: byId('result-wrong-div'),
    dailyBestAvg: byId('daily-best-avg'),
    dailyBestDistance: byId('daily-best-distance'),
    dailyAttempt: byId('daily-attempt'),
    dailyWrong: byId('daily-wrong'),
    dailyHistoryBody: byId('daily-history-body'),
    dailyHistorySum: byId('daily-history-sum'),
    dailyDiffWrap: byId('daily-diff'),
    diffBestAvg: byId('diff-best-avg'),
    diffWrong: byId('diff-wrong'),
    dailyResetButton: byId('daily-reset-button'),
    todayRank: byId('today-rank'),
    todayRankFirst: byId('rank-1'),
    todayRankSecond: byId('rank-2'),
    todayRankThird: byId('rank-3'),
    top3Message: byId('result-top3-message'),
    retryButton: byId('result-retry-button'),
    reviewButton: byId('result-review-button'),
    backButton: byId('result-back-button'),
  },
};

export default domRefs;
