const domRefs = {
  screens: {
    title: document.getElementById('title-screen'),
    settings: document.getElementById('settings-screen'),
    game: document.getElementById('game-screen'),
    result: document.getElementById('result-screen'),
  },
  title: {
    startButton: document.getElementById('title-start-button'),
  },
  settings: {
    presetSelect: document.getElementById('settings-preset'),
    modeInputs: document.querySelectorAll('input[name="mode"]'),
    digitInputs: document.querySelectorAll('input[name="digit"]'),
    carryCheckbox: document.getElementById('settings-carry'),
    playButton: document.getElementById('settings-play-button'),
  },
  game: {
    timeLeft: document.getElementById('game-time-left'),
    correctCount: document.getElementById('game-correct-count'),
    wrongCount: document.getElementById('game-wrong-count'),
    reviewProgress: document.getElementById('game-review-progress'),
    question: document.getElementById('game-question'),
    answerInput: document.getElementById('game-answer-input'),
    feedback: document.getElementById('game-feedback'),
  },
  result: {
    reviewBanner: document.getElementById('result-review-banner'),
    reviewMessage: document.getElementById('result-review-message'),
    nextActionButton: document.getElementById('result-next-action-button'),
    correctCount: document.getElementById('result-correct-count'),
    wrongCount: document.getElementById('result-wrong-count'),
    totalAnswered: document.getElementById('result-total-answered'),
    accuracy: document.getElementById('result-accuracy'),
    avgTime: document.getElementById('result-avg-time'),
    rateAdd: document.getElementById('result-rate-add'),
    rateSub: document.getElementById('result-rate-sub'),
    rateMul: document.getElementById('result-rate-mul'),
    rateDiv: document.getElementById('result-rate-div'),
    bestAvgTime: document.getElementById('result-best-avg'),
    wrongAdd: document.getElementById('result-wrong-add'),
    wrongSub: document.getElementById('result-wrong-sub'),
    wrongMul: document.getElementById('result-wrong-mul'),
    wrongDiv: document.getElementById('result-wrong-div'),
    dailyBestAvg: document.getElementById('daily-best-avg'),
    dailyAttempt: document.getElementById('daily-attempt'),
    dailyWrong: document.getElementById('daily-wrong'),
    dailyDiffWrap: document.getElementById('daily-diff'),
    diffBestAvg: document.getElementById('diff-best-avg'),
    diffWrong: document.getElementById('diff-wrong'),
    dailyResetButton: document.getElementById('daily-reset-button'),
    retryButton: document.getElementById('result-retry-button'),
    reviewButton: document.getElementById('result-review-button'),
    backButton: document.getElementById('result-back-button'),
  },
};

export default domRefs;
