const gameState = {
  playMode: 'free',
  selectedStageId: null,
  timeLimit: 60,
  timeLeft: 60,
  currentQuestion: null,
  correctCount: 0,
  wrongCount: 0,
  totalAnswered: 0,
  totalAnswerTimeMs: 0,
  questionStartAtMs: 0,
  answeredCountForTiming: 0,
  bestAvgSecSession: null,
  isReviewMode: false,
  reviewModes: [],
  reviewQuestionLimit: 10,
  reviewAnsweredCount: 0,
  reviewCompleted: false,
  speedMps: 2.0,
  distanceM: 0,
  currentStreak: 0,
  maxStreak: 0,
  maxSpeedMps: 8.0,
  minSpeedMps: 0.8,
  speedUp: 0.3,
  speedDown: 0.6,
  frictionMpsPerSec: 0.05,
  scalingLevel: 0,
  reviewSummary: {
    topMode: null,
    message: '',
    nextAction: null,
  },
  wrongByMode: {
    add: 0,
    sub: 0,
    mul: 0,
    div: 0,
  },
  attemptByMode: {
    add: 0,
    sub: 0,
    mul: 0,
    div: 0,
  },
  settings: {
    mode: 'add',
    digit: 1,
    carry: false,
  },
};

export default gameState;
